import { TestSeriesType } from "./types";

export const TestSeriesArr: TestSeriesType[] = [
  {
    id: 1,
    coverImage: "/images/card-cover.jpg",
    title: "IIT JAM Physics",
    date: "Starting from June 1st",
    price: 2999,
    discount: 20,
    discountedPrice: 2399,
    courseIncludes: [],
    description: "",
    duration: "",
    paperSetters: [],
    reviews: [],
    syllabus: [],
    totalTests: 0,
  },
  {
    id: 2,
    coverImage: "/images/card-cover.jpg",
    title: "JEST Physics",
    date: "Starting from July 1st",
    price: 2499,
    discount: 20,
    discountedPrice: 1999,
    courseIncludes: [],
    description: "",
    duration: "",
    paperSetters: [],
    reviews: [],
    syllabus: [],
    totalTests: 0,
  },
  {
    id: 3,
    coverImage: "/images/card-cover.jpg",
    title: "GATE Physics",
    date: "Starting from August 1st",
    price: 3499,
    discount: 20,
    discountedPrice: 2799,
    courseIncludes: [],
    description: "",
    duration: "",
    paperSetters: [],
    reviews: [],
    syllabus: [],
    totalTests: 0,
  },
];
